services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "80:80"
    depends_on:
      - mongodb
    command: fastapi run /code/src/main.py --port 80

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A messaging.core worker --loglevel=info
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
